### YamlMime:ManagedReference
items:
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  commentId: T:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  id: LayeredCharacterTypeSO.CharacterCreatorConfig
  parent: BlazerTech.CharacterManagement.Characters
  children:
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
  langs:
  - csharp
  - vb
  name: LayeredCharacterTypeSO.CharacterCreatorConfig
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  type: Class
  source:
    remote:
      path: Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/BlazerTech-Assets/BlazerTech-Character-Management-System.git
    id: CharacterCreatorConfig
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 131
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: >-
      [Serializable]

      public class LayeredCharacterTypeSO.CharacterCreatorConfig
    content.vb: >-
      <Serializable>

      Public Class LayeredCharacterTypeSO.CharacterCreatorConfig
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
  commentId: P:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
  id: PreviewController
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: PreviewController
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
  type: Property
  source:
    remote:
      path: Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/BlazerTech-Assets/BlazerTech-Character-Management-System.git
    id: PreviewController
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 135
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public RuntimeAnimatorController PreviewController { get; }
    parameters: []
    return:
      type: UnityEngine.RuntimeAnimatorController
    content.vb: Public Property PreviewController As RuntimeAnimatorController
  overload: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController*
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
  commentId: P:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
  id: PreviewSprite
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: PreviewSprite
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
  type: Property
  source:
    remote:
      path: Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/BlazerTech-Assets/BlazerTech-Character-Management-System.git
    id: PreviewSprite
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 137
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public Sprite PreviewSprite { get; set; }
    parameters: []
    return:
      type: UnityEngine.Sprite
    content.vb: Public Property PreviewSprite As Sprite
  overload: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite*
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
  commentId: P:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
  id: CharacterPreviewAnimationOptions
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: CharacterPreviewAnimationOptions
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
  type: Property
  source:
    remote:
      path: Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/BlazerTech-Assets/BlazerTech-Character-Management-System.git
    id: CharacterPreviewAnimationOptions
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 138
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption[] CharacterPreviewAnimationOptions { get; }
    parameters: []
    return:
      type: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption[]
    content.vb: Public Property CharacterPreviewAnimationOptions As LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption()
  overload: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions*
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
  commentId: P:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
  id: BaseLayer
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: BaseLayer
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
  type: Property
  source:
    remote:
      path: Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/BlazerTech-Assets/BlazerTech-Character-Management-System.git
    id: BaseLayer
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 142
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public CharacterLayerDefinitionSO BaseLayer { get; set; }
    parameters: []
    return:
      type: BlazerTech.CharacterManagement.Characters.CharacterLayerDefinitionSO
    content.vb: Public Property BaseLayer As CharacterLayerDefinitionSO
  overload: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer*
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
  commentId: P:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
  id: BL_DefaultOptionIndex
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: BL_DefaultOptionIndex
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
  type: Property
  source:
    remote:
      path: Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/BlazerTech-Assets/BlazerTech-Character-Management-System.git
    id: BL_DefaultOptionIndex
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BT-CMS/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 146
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public int BL_DefaultOptionIndex { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property BL_DefaultOptionIndex As Integer
  overload: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex*
references:
- uid: BlazerTech.CharacterManagement.Characters
  commentId: N:BlazerTech.CharacterManagement.Characters
  href: BlazerTech.html
  name: BlazerTech.CharacterManagement.Characters
  nameWithType: BlazerTech.CharacterManagement.Characters
  fullName: BlazerTech.CharacterManagement.Characters
  spec.csharp:
  - uid: BlazerTech
    name: BlazerTech
    href: BlazerTech.html
  - name: .
  - uid: BlazerTech.CharacterManagement
    name: CharacterManagement
    href: BlazerTech.CharacterManagement.html
  - name: .
  - uid: BlazerTech.CharacterManagement.Characters
    name: Characters
    href: BlazerTech.CharacterManagement.Characters.html
  spec.vb:
  - uid: BlazerTech
    name: BlazerTech
    href: BlazerTech.html
  - name: .
  - uid: BlazerTech.CharacterManagement
    name: CharacterManagement
    href: BlazerTech.CharacterManagement.html
  - name: .
  - uid: BlazerTech.CharacterManagement.Characters
    name: Characters
    href: BlazerTech.CharacterManagement.Characters.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController*
  commentId: Overload:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.html#BlazerTech_CharacterManagement_Characters_LayeredCharacterTypeSO_CharacterCreatorConfig_PreviewController
  name: PreviewController
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewController
- uid: UnityEngine.RuntimeAnimatorController
  commentId: T:UnityEngine.RuntimeAnimatorController
  parent: UnityEngine
  isExternal: true
  name: RuntimeAnimatorController
  nameWithType: RuntimeAnimatorController
  fullName: UnityEngine.RuntimeAnimatorController
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite*
  commentId: Overload:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.html#BlazerTech_CharacterManagement_Characters_LayeredCharacterTypeSO_CharacterCreatorConfig_PreviewSprite
  name: PreviewSprite
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewSprite
- uid: UnityEngine.Sprite
  commentId: T:UnityEngine.Sprite
  parent: UnityEngine
  isExternal: true
  name: Sprite
  nameWithType: Sprite
  fullName: UnityEngine.Sprite
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions*
  commentId: Overload:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.html#BlazerTech_CharacterManagement_Characters_LayeredCharacterTypeSO_CharacterCreatorConfig_CharacterPreviewAnimationOptions
  name: CharacterPreviewAnimationOptions
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOptions
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption[]
  isExternal: true
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption.html
  name: CharacterPreviewAnimationOption[]
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption[]
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption[]
  nameWithType.vb: LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption()
  fullName.vb: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption()
  name.vb: CharacterPreviewAnimationOption()
  spec.csharp:
  - uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption
    name: CharacterPreviewAnimationOption
    href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption.html
  - name: '['
  - name: ']'
  spec.vb:
  - uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption
    name: CharacterPreviewAnimationOption
    href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewAnimationOption.html
  - name: (
  - name: )
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer*
  commentId: Overload:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.html#BlazerTech_CharacterManagement_Characters_LayeredCharacterTypeSO_CharacterCreatorConfig_BaseLayer
  name: BaseLayer
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseLayer
- uid: BlazerTech.CharacterManagement.Characters.CharacterLayerDefinitionSO
  commentId: T:BlazerTech.CharacterManagement.Characters.CharacterLayerDefinitionSO
  parent: BlazerTech.CharacterManagement.Characters
  href: BlazerTech.CharacterManagement.Characters.CharacterLayerDefinitionSO.html
  name: CharacterLayerDefinitionSO
  nameWithType: CharacterLayerDefinitionSO
  fullName: BlazerTech.CharacterManagement.Characters.CharacterLayerDefinitionSO
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex*
  commentId: Overload:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.html#BlazerTech_CharacterManagement_Characters_LayeredCharacterTypeSO_CharacterCreatorConfig_BL_DefaultOptionIndex
  name: BL_DefaultOptionIndex
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BL_DefaultOptionIndex
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
